# Generated by Django 4.1.4 on 2022-12-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_pet_photos_alter_pet_birthday_delete_petimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="photos",
        ),
        migrations.AddField(
            model_name="image",
            name="pet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="pets.pet",
            ),
            preserve_default=False,
        ),
    ]
